# Exploring possible targets for XRISM - 2024

## Import Statements

In [1]:
from astropy.units import Quantity
import astropy.units as u
from astropy.cosmology import FlatLambdaCDM
from astropy.coordinates import SkyCoord
from astropy.table import Table
from astropy.io import fits
import pandas as pd
pd.options.display.max_rows = 999
pd.set_option("max_colwidth", 100)
pd.set_option('display.max_columns', 500)
import numpy as np
import os
from tqdm import tqdm
from matplotlib import pyplot as plt
import warnings

from xga.products import Image
from xga.imagetools.misc import physical_rad_to_pix
from xga.sourcetools.misc import rad_to_ang
from xga.imagetools.profile import annular_mask
from xga.products import ExpMap

%matplotlib inline
warnings.filterwarnings('ignore')

## Define the cosmology

In [2]:
cosmo = FlatLambdaCDM(70, 0.3)

## Read in the sample

In [3]:
samp = pd.read_csv("../../sample_files/lovoccs_southnorth.csv")
samp['LoVoCCS_name'] = samp['LoVoCCSID'].apply(lambda x: 'LoVoCCS-' + str(x))

check = pd.read_csv(("../../../LoVoCCS-Sample/paper_specific_subsamples/proposals/NuSTAR/"
                     "lovoccs_checklist_lite.csv"))

check['Name'] = check['Name'].apply(lambda x: x.replace('RXC ', 'RXC').replace("RBS ", "RBS")
                                    .replace("APMCC ", "APMCC").replace("MKW ", "MKW"))

In [4]:
on_other = pd.merge(samp, check, left_on="other_names", right_on="Name", how="right")
on_alt = pd.merge(samp, check, left_on="alt_name", right_on="Name", how="right")
rel_samp = pd.concat([on_other[~on_other['LoVoCCSID'].isna()], 
                      on_alt[~on_alt['LoVoCCSID'].isna()]]).drop_duplicates('LoVoCCSID')
rel_samp['LoVoCCSID'] = rel_samp['LoVoCCSID'].astype(int)
rel_samp = rel_samp.reset_index(drop=True)

In [5]:
check[~check['Name'].isin(rel_samp.Name)]

Empty DataFrame
Columns: [ID, Name, RA, DEC, Redshift, Newly processed, Fully observed, Comments]
Index: []

We reduce the sample to only those clusters which have been fully observed by our optical survey:

In [6]:
rel_samp = rel_samp[rel_samp['Fully observed'] == 'yes'].reset_index(drop=True)
rel_samp['Fully observed'].value_counts()
rel_samp.to_csv('under_consideration.csv', index=False)

In [7]:
rel_samp['sub_samp'].value_counts()

sub_samp
south    79
north     3
Name: count, dtype: int64

In [8]:
rel_samp

,name,MCXC,LoVoCCSID,LoVoCCS_name,ra,dec,redshift,L500,M500,R500,alt_name,other_names,Notes,sub_samp,old_LoVoCCSID,ID,Name,RA,DEC,Redshift,Newly processed,Fully observed,Comments
0,MCXCJ1510.9+0543,J1510.9+0543,1,LoVoCCS-1,227.729167,5.720000,0.0766,8.726709,7.2708,1.3344,A2029,A2029,NaN,south,1.0,1,A2029,227.73,5.72,0.0766,1.0,yes,"with A2033, southern infalling group"
1,MCXCJ0258.9+1334,J0258.9+1334,2,LoVoCCS-2,44.739583,13.579444,0.0739,6.088643,5.8488,1.2421,RXCJ0258.9+1334,A401,L,south,2.0,2,A401,44.74,13.58,0.0739,1.0,yes,Bridge of galaxies between A401/A399 -- similar to gas
2,MCXCJ0041.8-0918,J0041.8-0918,4,LoVoCCS-4,10.458750,-9.301944,0.0555,5.100085,5.3163,1.2103,RXCJ0041.8-0918,A85,"L,losStr",south,4.0,3,A85,10.46,-9.30,0.0555,1.0,yes,NaN
3,MCXCJ2012.5-5649,J2012.5-5649,5,LoVoCCS-5,303.127100,-56.831900,0.0556,4.871933,5.1696,1.1990,RXCJ2012.5-5649,A3667,"L,losStr",south,901.0,4,A3667,303.13,-56.83,0.0556,1.0,yes,NaN
4,MCXCJ2201.9-5956,J2201.9-5956,7,LoVoCCS-7,330.483333,-59.949444,0.0980,4.204419,4.5890,1.1367,RXCJ2201.9-5956,A3827,NaN,south,6.0,5,A3827,330.48,-59.95,0.0980,1.0,yes,"Currently using A3825 catalogs. Note the 2 clusters are at very different redshifts, but RS colo..."
5,MCXCJ0431.4-6126,J0431.4-6126,9,LoVoCCS-9,67.850417,-61.443889,0.0589,3.977333,4.5579,1.1485,RXCJ0431.4-6126,A3266,NaN,south,8.0,6,A3266,67.85,-61.44,0.0589,1.0,yes,NaN
6,MCXCJ1259.3-0411,J1259.3-0411,10,LoVoCCS-10,194.839583,-4.194722,0.0845,3.853573,4.3928,1.1252,RXCJ1259.3-0411,A1651,NaN,south,9.0,7,A1651,194.84,-4.19,0.0845,1.0,yes,NaN
7,MCXCJ0909.1-0939,J0909.1-0939,11,LoVoCCS-11,137.285000,-9.666111,0.0542,3.849660,4.4824,1.1439,RXCJ0909.1-0939,A754,NaN,south,10.0,8,A754,137.28,-9.67,0.0542,1.0,yes,"2 peaks in RS galaxy density map, lensing peak is mainly at BCG"
8,MCXCJ1347.4-3250,J1347.4-3250,12,LoVoCCS-12,206.868333,-32.849722,0.0391,3.819920,4.5067,1.1514,RXCJ1347.4-3250,A3571,L,south,11.0,9,A3571,206.87,-32.85,0.0391,1.0,yes,eRosita
9,MCXCJ0317.9-4414,J0317.9-4414,13,LoVoCCS-13,49.493750,-44.238889,0.0752,3.815928,4.3948,1.1288,RXCJ0317.9-4414,A3112,NaN,south,12.0,10,A3112,49.49,-44.24,0.0752,1.0,yes,"Horologium Supercluster with A3128, A3158, A3266. Xray mass is very close to the lensing mass (S..."
10,MCXCJ0257.8+1302,J0257.8+1302,14,LoVoCCS-14,44.457500,13.049167,0.0722,3.592916,4.2452,1.1169,RXCJ0257.8+1302,A399,NaN,south,13.0,11,A399,44.46,13.05,0.0722,1.0,yes,NaN
11,MCXCJ2325.3-1207,J2325.3-1207,15,LoVoCCS-15,351.333333,-12.127222,0.0852,3.557935,4.1821,1.1066,RXCJ2325.3-1207,A2597,NaN,south,14.0,12,A2597,351.33,-12.13,0.0852,1.0,yes,NaN
12,MCXCJ1258.6-0145,J1258.6-0145,18,LoVoCCS-18,194.671250,-1.756944,0.0845,3.470646,4.1213,1.1015,RXCJ1258.6-0145,A1650,NaN,south,17.0,13,A1650,194.67,-1.76,0.0845,NaN,yes,NaN
13,MCXCJ0052.7-8015,J0052.7-8015,19,LoVoCCS-19,13.187083,-80.266389,0.1141,3.393306,3.9812,1.0783,RXCJ0052.7-8015,A2837,NaN,south,18.0,14,A2837,13.19,-80.27,0.1141,1.0,yes,NaN
14,MCXCJ1327.9-3130,J1327.9-3130,21,LoVoCCS-21,201.989583,-31.502500,0.0480,3.138519,3.9741,1.1010,RXCJ1327.9-3130,A3558,"P,GR6,losStr",south,20.0,16,A3558,201.99,-31.50,0.0480,1.0,yes,Shapley supercluster
15,MCXCJ2034.7-3548,J2034.7-3548,22,LoVoCCS-22,308.699583,-35.813333,0.0894,2.963013,3.7297,1.0637,RXCJ2034.7-3548,A3695,"L,losStr",south,21.0,17,A3695,308.70,-35.81,0.0894,1.0,yes,NaN
16,MCXCJ2249.9-6425,J2249.9-6425,24,LoVoCCS-24,342.487500,-64.429444,0.0940,2.828545,3.6139,1.0510,RXCJ2249.9-6425,A3921,losStr,south,23.0,18,A3921,342.49,-64.43,0.0940,1.0,yes,"Offset between peaks of mass map, BCG/Xray. Merging cluster."
17,MCXCJ2214.5-1022,J2214.5-1022,26,LoVoCCS-26,333.635833,-10.371667,0.0980,2.770068,3.5581,1.0442,RXCJ2214.5-1022,A2426,NaN,south,25.0,19,A2426,333.64,-10.37,0.0980,NaN,yes,NaN
18,MCXCJ0342.8-5338,J0342.8-5338,27,LoVoCCS-27,55.724583,-53.635278,0.0590,2.764920,3.6513,1.0667,RXCJ0342.8-5338,A3158,"L,losStr",south,26.0,20,A3158,55.72,-53.64,0.0590,1.0,yes,Horologium supercluster
19,MCXCJ0042.1-2832,J0042.1-2832,29,LoVoCCS-29,10.536250,-28.535833,0.1082,2.734146,3.5046,1.0355,RXCJ0042.1-2832,A2811,losStr,south,28.0,22,A2811,10.54,-28.54,0.1082,1.0,yes,NaN
20,MCXCJ0918.1-1205,J0918.1-1205,30,LoVoCCS-30,139.527083,-12.093333,0.0539,2.716018,3.6243,1.0658,RXCJ0918.1-1205,A780,BX,south,29.0,23,A780,139.53,-12.09,0.0539,1.0,yes,The BCG is Hydra A (also 3C 218). The mass map extend to East (check montage) and seems also in ...
21,MCXCJ2210.3-1210,J2210.3-1210,31,LoVoCCS-31,332.582083,-12.176111,0.0846,2.672473,3.5139,1.0445,RXCJ2210.3-1210,A2420,NaN,south,30.0,24,A2420,332.58,-12.18,0.0846,1.0,yes,NaN
22,MCXCJ1130.3-1434,J1130.3-1434,33,LoVoCCS-33,172.581250,-14.583056,0.1068,2.605129,3.4062,1.0262,RXCJ1130.3-1434,A1285,NaN,south,32.0,25,A1285,172.58,-14.58,0.1068,1.0,yes,NaN
23,MCXCJ2246.3-5243,J2246.3-5243,35,LoVoCCS-35,341.577500,-52.729444,0.0965,2.565193,3.3988,1.0289,RXCJ2246.3-5243,A3911,L,south,34.0,26,A3911,341.58,-52.73,0.0965,1.0,yes,NaN
24,MCXCJ2331.2-3630,J2331.2-3630,37,LoVoCCS-37,352.802917,-36.506667,0.0957,2.419356,3.2815,1.0172,RXCJ2331.2-3630,A4010,NaN,south,36.0,27,A4010,352.80,-36.51,0.0957,1.0,yes,Mass map peak offset (reason?). XMM centered at BCG. https://arxiv.org/pdf/2204.02699.pdf https:...
25,MCXCJ1518.7+0613,J1518.7+0613,39,LoVoCCS-39,229.690000,6.231111,0.1021,2.241343,3.1180,0.9979,RXCJ1518.7+0613,A2055,C,south,38.0,28,A2055,229.69,6.23,0.1021,1.0,yes,NaN
26,MCXCJ1330.8-0152,J1330.8-0152,41,LoVoCCS-41,202.707917,-1.872778,0.0852,2.127767,3.0567,0.9968,RXCJ1330.8-0152,A1750,"DL,large elongation towards NE,losStr",south,40.0,30,A1750,202.71,-1.87,0.0852,1.0,yes,There're 2 centers -- RS and mass peaks are different -- merging.
27,MCXCJ2154.1-5751,J2154.1-5751,42,LoVoCCS-42,328.538333,-57.855278,0.0760,2.097956,3.0499,0.9991,RXCJ2154.1-5751,A3822,losStr,south,41.0,31,A3822,328.54,-57.86,0.0760,NaN,yes,NaN
28,MCXCJ1132.8+1428,J1132.8+1428,43,LoVoCCS-43,173.220833,14.468889,0.0834,2.074613,3.0137,0.9927,RXCJ1132.8+1428,A1307,NaN,south,42.0,32,A1307,173.22,14.47,0.0834,1.0,yes,NaN
29,MCXCJ2149.1-3041,J2149.1-3041,44,LoVoCCS-44,327.280833,-30.698611,0.1184,2.053481,2.9219,0.9713,RXCJ2149.1-3041,A3814,NaN,south,43.0,33,A3814,327.28,-30.70,0.1184,NaN,yes,NaN
30,MCXCJ0145.0-5300,J0145.0-5300,45,LoVoCCS-45,26.259583,-53.013889,0.1168,2.010759,2.8880,0.9680,RXCJ0145.0-5300,A2941,NaN,south,44.0,34,A2941,26.26,-53.01,0.1168,NaN,yes,NaN
31,MCXCJ2223.8-0138,J2223.8-0138,46,LoVoCCS-46,335.970417,-1.637778,0.0906,1.903100,2.8449,0.9716,RXCJ2223.8-0138,A2440,NaN,south,45.0,35,A2440,335.97,-1.64,0.0906,1.0,yes,NaN
32,MCXCJ1257.1-1724,J1257.1-1724,48,LoVoCCS-48,194.290417,-17.400278,0.0473,1.897483,2.9254,0.9944,RXCJ1257.1-1724,A1644,L,south,47.0,36,A1644,194.29,-17.40,0.0473,NaN,yes,NaN
33,MCXCJ1141.4-1216,J1141.4-1216,49,LoVoCCS-49,175.351250,-12.272222,0.1195,1.893646,2.7789,0.9548,RXCJ1141.4-1216,A1348,"X,losStr",south,48.0,37,A1348,175.35,-12.27,0.1195,1.0,yes,NaN
34,MCXCJ2218.0-6511,J2218.0-6511,51,LoVoCCS-51,334.522917,-65.185000,0.0951,1.858113,2.7949,0.9644,RXCJ2218.0-6511,RBS1847,NaN,south,50.0,38,RBS1847,334.52,-65.19,0.0951,1.0,yes,NaN
35,MCXCJ0433.6-1315,J0433.6-1315,52,LoVoCCS-52,68.410000,-13.259167,0.0326,1.852990,2.9118,0.9974,RXCJ0433.6-1315,A496,NaN,south,51.0,39,A496,68.41,-13.26,0.0326,NaN,yes,NaN
36,MCXCJ0006.0-3443,J0006.0-3443,57,LoVoCCS-57,1.512500,-34.724167,0.1147,1.809494,2.7122,0.9486,RXCJ0006.0-3443,A2721,NaN,south,56.0,43,A2721,1.51,-34.72,0.1147,NaN,yes,NaN
37,MCXCJ2134.2-1328,J2134.2-1328,58,LoVoCCS-58,323.568750,-13.480000,0.0897,1.793951,2.7460,0.9604,RXCJ2134.2-1328,A2351,B,south,57.0,44,A2351,323.57,-13.48,0.0897,1.0,yes,NaN
38,MCXCJ2226.0+1722,J2226.0+1722,61,LoVoCCS-61,336.510833,17.378056,0.1072,1.706366,2.6308,0.9414,A2443,A2443,NaN,north,60.0,46,A2443,336.51,17.38,0.1072,1.0,yes,Multiple BCGs; the mass peak locates at one BCG.
39,MCXCJ1516.3+0005,J1516.3+0005,63,LoVoCCS-63,229.080000,0.097778,0.1181,1.689631,2.5949,0.9337,RXCJ1516.3+0005,A2050,NaN,south,62.0,47,A2050,229.08,0.10,0.1181,1.0,yes,NaN
40,MCXCJ2143.9-5637,J2143.9-5637,64,LoVoCCS-64,325.992917,-56.626389,0.0824,1.678567,2.6504,0.9514,RXCJ2143.9-5637,APMCC699,NaN,south,63.0,48,APMCC699,325.99,-56.63,0.0824,NaN,yes,NaN
41,MCXCJ1326.9-2710,J1326.9-2710,65,LoVoCCS-65,201.725000,-27.183333,0.0458,1.667482,2.7065,0.9694,RXCJ1326.9-2710,A1736,L,south,64.0,49,A1736,201.73,-27.18,0.0458,NaN,yes,NaN
42,MCXCJ2152.4-1933,J2152.4-1933,66,LoVoCCS-66,328.100000,-19.565000,0.0943,1.663138,2.6137,0.9433,RXCJ2152.4-1933,A2384,"PB,GR10",south,65.0,50,A2384,328.10,-19.57,0.0943,1.0,yes,NaN
43,MCXCJ2357.0-3445,J2357.0-3445,67,LoVoCCS-67,359.259583,-34.760556,0.0475,1.629622,2.6658,0.9640,RXCJ2357.0-3445,A4059,L,south,66.0,51,A4059,359.26,-34.76,0.0475,1.0,yes,Lensing signal is not strong.
44,MCXCJ2321.5-4153,J2321.5-4153,69,LoVoCCS-69,350.389167,-41.898889,0.0894,1.625536,2.5863,0.9415,RXCJ2321.5-4153,A3998,losStr,south,68.0,52,A3998,350.39,-41.90,0.0894,1.0,yes,"Although deep, no clear lensing signal? Only from ACOS1111? Actually ~2.5 at R~5000pix"
45,MCXCJ2209.3-5148,J2209.3-5148,74,LoVoCCS-74,332.347083,-51.815000,0.1065,1.552700,2.4850,0.9239,RXCJ2209.3-5148,A3836,NaN,south,73.0,55,A3836,332.35,-51.82,0.1065,NaN,yes,NaN
46,MCXCJ2307.2-1513,J2307.2-1513,75,LoVoCCS-75,346.813750,-15.228333,0.1110,1.552593,2.4769,0.9215,RXCJ2307.2-1513,A2533,NaN,south,74.0,56,A2533,346.81,-15.23,0.1110,1.0,yes,The BCG looks interesting — looks like there’s some dust lane/disk/jet. (http://etheses.dur.ac.u...
47,MCXCJ2313.0-2137,J2313.0-2137,76,LoVoCCS-76,348.253750,-21.631944,0.0871,1.509152,2.4758,0.9286,RXCJ2313.0-2137,A2556,NaN,south,75.0,57,A2556,348.25,-21.63,0.0871,1.0,yes,"Note nearby clusters A2550, AQ, SPT"
48,MCXCJ1521.8+0742,J1521.8+0742,79,LoVoCCS-79,230.458333,7.708889,0.0442,1.482131,2.5215,0.9473,RXCJ1521.8+0742,MKW3s,NaN,south,78.0,58,MKW3s,230.46,7.71,0.0442,NaN,yes,"Near A2052, A2063"
49,MCXCJ0328.6-5542,J0328.6-5542,80,LoVoCCS-80,52.156250,-55.712778,0.0853,1.467361,2.4368,0.9243,RXCJ0328.6-5542,A3126,NaN,south,79.0,59,A3126,52.16,-55.71,0.0853,1.0,yes,Special mass map -- but matches DES Y3 Weiner map. Hints of high redshift red galaxies.
50,MCXCJ0345.9-2416,J0345.9-2416,81,LoVoCCS-81,56.483333,-24.280278,0.1057,1.462214,2.3970,0.9131,RXCJ0345.9-2416,A458,NaN,south,80.0,60,A458,56.48,-24.28,0.1057,NaN,yes,NaN
51,MCXCJ0102.7-2152,J0102.7-2152,82,LoVoCCS-82,15.675417,-21.873611,0.0569,1.460216,2.4774,0.9379,RXCJ0102.7-2152,A133,NaN,south,81.0,61,A133,15.68,-21.87,0.0569,1.0,yes,"Collaborator's observation (Ana Costa, Yara Jaffe, 2022B-791264)."
52,MCXCJ1516.7+0701,J1516.7+0701,83,LoVoCCS-83,229.183333,7.018611,0.0353,1.442058,2.4945,0.9465,RXCJ1516.7+0701,A2052,NaN,south,82.0,62,A2052,229.18,7.02,0.0353,NaN,yes,"Near A2055,A2063,MKW3s"
53,MCXCJ2216.2-0920,J2216.2-0920,84,LoVoCCS-84,334.064583,-9.340000,0.0825,1.438718,2.4124,0.9220,RXCJ2216.2-0920,A2428,NaN,south,83.0,63,A2428,334.06,-9.34,0.0825,1.0,yes,NaN
54,MCXCJ2312.3-2130,J2312.3-2130,89,LoVoCCS-89,348.086250,-21.500556,0.1108,1.431443,2.3576,0.9065,RXCJ2312.3-2130,A2554,losStr,south,88.0,66,A2554,348.09,-21.50,0.1108,1.0,yes,Near A2556
55,MCXCJ1511.3+0619,J1511.3+0619,90,LoVoCCS-90,227.847917,6.318889,0.0817,1.406968,2.3811,0.9183,A2033,A2033,NaN,south,89.0,67,A2033,227.85,6.32,0.0817,1.0,yes,Done Together with A2029
56,MCXCJ2319.1-4206,J2319.1-4206,91,LoVoCCS-91,349.775000,-42.113889,0.0450,1.405897,2.4403,0.9367,MS2316.3-4222,ACOS1111,NaN,south,90.0,68,ACOS1111,349.77,-42.11,0.0450,NaN,yes,Near A3998
57,MCXCJ0627.2-5428,J0627.2-5428,93,LoVoCCS-93,96.810000,-54.470000,0.0506,1.375477,2.3989,0.9298,RXCJ0627.2-5428,A3395,"PL,GR3",south,902.0,70,A3395,96.81,-54.47,0.0506,NaN,yes,NaN
58,MCXCJ1244.6-1159,J1244.6-1159,94,LoVoCCS-94,191.158333,-11.985278,0.0963,1.375433,2.3246,0.9066,RXCJ1244.6-1159,A1606,NaN,south,92.0,71,A1606,191.16,-11.99,0.0963,NaN,yes,NaN
59,MCXCJ1602.3+1601,J1602.3+1601,97,LoVoCCS-97,240.577917,16.020000,0.0353,1.358380,2.4052,0.9351,A2147,A2147,NaN,north,95.0,72,A2147,240.58,16.02,0.0353,1.0,yes,Clear shift of lensing peak -- Probably it's caused by nearby clusters. Part of Hercules superc...
60,MCXCJ2354.2-1024,J2354.2-1024,98,LoVoCCS-98,358.555833,-10.412778,0.0765,1.336537,2.3160,0.9113,RXCJ2354.2-1024,A2670,"B,losStr",south,96.0,73,A2670,358.56,-10.41,0.0765,1.0,yes,NaN
61,MCXCJ1257.2-3022,J1257.2-3022,99,LoVoCCS-99,194.320417,-30.376944,0.0554,1.323277,2.3354,0.9201,RXCJ1257.2-3022,A3532,"B,GR5",south,97.0,74,A3532,194.32,-30.38,0.0554,NaN,yes,Near A3528. A3530. eRosita data.
62,MCXCJ0912.4+1556,J0912.4+1556,100,LoVoCCS-100,138.124167,15.943056,0.0851,1.312476,2.2769,0.9037,A763,A763,NaN,north,98.0,75,A763,138.12,15.94,0.0851,1.0,yes,NaN
63,MCXCJ1516.5-0056,J1516.5-0056,101,LoVoCCS-101,229.141667,-0.948889,0.1198,1.296543,2.2053,0.8839,RXCJ1516.5-0056,A2051,NaN,south,99.0,76,A2051,229.14,0.95,0.1198,NaN,yes,Near A2050 (1 deg). Small BCG.
64,MCXCJ0330.0-5235,J0330.0-5235,121,LoVoCCS-121,52.502917,-52.596111,0.0624,1.101682,2.0786,0.8831,RXCJ0330.0-5235,A3128,"DL,two maxima/NE-SW",south,118.0,90,A3128,52.50,-52.60,0.0624,1.0,yes,Merging cluster with multiple central galaxies. A3125 small clump SW. No clear connection with A...
65,MCXCJ1027.9-0647,J1027.9-0647,122,LoVoCCS-122,156.998333,-6.796111,0.1176,1.095941,1.9936,0.8553,RXCJ1027.9-0647,A1023,X *,south,119.0,91,A1023,157.00,-6.80,0.1176,1.0,yes,NaN
66,MCXCJ1254.6-2913,J1254.6-2913,123,LoVoCCS-123,193.672500,-29.223333,0.0544,1.093054,2.0799,0.8855,RXCJ1254.6-2913,A3528,"PB,GR4",south,120.0,92,A3528,193.67,-29.22,0.0544,NaN,yes,"With A3532, A3530 nearby. eRosita data."
67,MCXCJ1113.3+0231,J1113.3+0231,124,LoVoCCS-124,168.336250,2.532222,0.0780,1.090082,2.0432,0.8736,RXCJ1113.3+0231,A1205,NaN,south,121.0,93,A1205,168.34,2.53,0.0780,1.0,yes,Lensing mainly comes from the nearby background cluster?
68,MCXCJ0425.8-0833,J0425.8-0833,128,LoVoCCS-128,66.464167,-8.559167,0.0397,1.080714,2.0861,0.8905,RXCJ0425.8-0833,RBS0540,X,south,125.0,96,RBS0540,66.46,-8.56,0.0397,1.0,yes,NaN
69,MCXCJ0910.6-1034,J0910.6-1034,131,LoVoCCS-131,137.651250,-10.581111,0.0916,1.063423,1.9936,0.8627,RXCJ0910.6-1034,A761,NaN,south,128.0,97,A761,137.65,-10.58,0.0916,NaN,yes,NaN
70,MCXCJ2158.4-6023,J2158.4-6023,134,LoVoCCS-134,329.613333,-60.399444,0.0750,1.050267,2.0015,0.8685,RXCJ2158.4-6023,A3825,losStr,south,131.0,99,A3825,329.61,-60.40,0.0750,1.0,yes,Very weak lensing signal. With A3827
71,MCXCJ1558.3-1410,J1558.3-1410,20,LoVoCCS-20,239.596667,-14.167778,0.0970,3.179797,3.8731,1.0745,RXCJ1558.3-1410,NaN,B,south,19.0,15,RXCJ1558.3-1410,239.60,-14.17,0.0970,NaN,yes,NaN
72,MCXCJ1217.6+0339,J1217.6+0339,28,LoVoCCS-28,184.419167,3.662500,0.0766,2.744796,3.5915,1.0548,RXCJ1217.6+0339,ZwCl1215,NaN,south,27.0,21,RXCJ1217.6+0339,184.42,3.66,0.0766,1.0,yes,NaN
73,MCXCJ1539.5-8335,J1539.5-8335,40,LoVoCCS-40,234.891250,-83.592222,0.0728,2.235082,3.1770,1.0138,RXCJ1539.5-8335,NaN,NaN,south,39.0,29,RXCJ1539.5-8335,234.89,-83.59,0.0728,1.0,yes,NaN
74,MCXCJ2344.2-0422,J2344.2-0422,53,LoVoCCS-53,356.066667,-4.367500,0.0786,1.852614,2.8221,0.9727,RXCJ2344.2-0422,NaN,NaN,south,52.0,40,RXCJ2344.2-0422,356.07,-4.37,0.0786,NaN,yes,NaN
75,MCXCJ1215.4-3900,J1215.4-3900,55,LoVoCCS-55,183.870833,-39.015278,0.1190,1.834651,2.7267,0.9489,RXCJ1215.4-3900,NaN,NaN,south,54.0,41,RXCJ1215.4-3900,183.87,-39.02,0.1190,1.0,yes,NaN
76,MCXCJ2313.9-4244,J2313.9-4244,56,LoVoCCS-56,348.494167,-42.733889,0.0564,1.811143,2.8261,0.9802,RXCJ2313.9-4244,S1101,NaN,south,55.0,42,RXCJ2313.9-4244,348.49,-42.73,0.0564,1.0,yes,No clear lensing signal. Could be affected by nearby clusters. Close to ACOS1111.
77,MCXCJ2218.2-0350,J2218.2-0350,60,LoVoCCS-60,334.571250,-3.834167,0.0901,1.725034,2.6804,0.9526,RXCJ2218.2-0350,MS2215,"D,two maxima/NEE-SWW",south,59.0,45,RXCJ2218.2-0350,334.57,-3.83,0.0901,1.0,yes,Unrelaxed
78,MCXCJ1139.4-3327,J1139.4-3327,108,LoVoCCS-108,174.863750,-33.453889,0.1076,1.218610,2.1420,0.8789,RXCJ1139.4-3327,NaN,NaN,south,106.0,81,RXCJ1139.4-3327,174.86,-33.45,0.1076,1.0,yes,NaN
79,MCXCJ0351.1-8212,J0351.1-8212,110,LoVoCCS-110,57.787100,-82.216700,0.0613,1.200899,2.1924,0.8992,RXCJ0351.1-8212,S0405,L,south,900.0,83,RXCJ0351.1-8212,57.79,-82.22,0.0613,1.0,yes,Strange offset between BCG and mass peak. Two well-separated clumps in the mass map. Should chec...
80,MCXCJ1332.9-2519,J1332.9-2519,116,LoVoCCS-116,203.232500,-25.323889,0.1199,1.139833,2.0385,0.8610,RXCJ1332.9-2519,NaN,X,south,113.0,86,RXCJ1332.9-2519,203.23,-25.32,0.1199,1.0,yes,Not very clear lensing peak
81,MCXCJ0821.0+0751,J0821.0+0751,119,LoVoCCS-119,125.257500,7.866111,0.1100,1.110969,2.0211,0.8614,RXCJ0821.0+0751,RXJ0820.9+0751,NaN,south,116.0,88,RXCJ0821.0+0751,125.26,7.87,0.1100,1.0,yes,NaN

In [9]:
stop

NameError: name 'stop' is not defined

## NuSTAR coverage of the LoVoCCS sample

In [ ]:
field_nustar_cov_frac = []
r500_nustar_cov_frac = []
rvir_nustar_cov_frac = []

for row_ind, row in samp.iterrows():
    cov_path = "../../outputs/coverage_maps/fits/{n}_550pix_20.0arcsec.fits".format(n=row["LoVoCCS_name"])
    cur_cheese = ExpMap(cov_path, '', '', '', '', '', Quantity(0.5, 'keV'), Quantity(2.0, 'keV'))
    with fits.open(cov_path) as covero:
        if row_ind == 0:
            print(covero[0].header['MISSION*'])
            
        cov_arr = covero[0].data
        nustar_cov_arr = cov_arr[4, :, :]
        
        field_nustar_cov_frac.append(nustar_cov_arr.sum() / (nustar_cov_arr.shape[0]*nustar_cov_arr.shape[1]))
        
        pix_cen = Quantity([nustar_cov_arr.shape[0]/2, nustar_cov_arr.shape[1]/2], 'pix').round(0).astype(int)
        rad = Quantity(row['R500'], 'Mpc')
        
        pix_rad = physical_rad_to_pix(cur_cheese, rad, pix_cen, row['redshift'], cosmo)
        
        rad_mask = annular_mask(pix_cen, np.array([0]), np.array([pix_rad.value]), nustar_cov_arr.shape)
        msk_nustar_cov = nustar_cov_arr*rad_mask
        r500_nustar_cov_frac.append(msk_nustar_cov.sum() / rad_mask.sum())
        
        samp.loc[row_ind, 'NUSTAR_R500_FRAC'] = r500_nustar_cov_frac[row_ind]

In [ ]:
field_nustar_cov_frac = []
r500_nustar_cov_frac = []
rvir_nustar_cov_frac = []

for row_ind, row in rel_samp.iterrows():
    cov_path = "../../outputs/coverage_maps/fits/{n}_550pix_20.0arcsec.fits".format(n=row["LoVoCCS_name"])
    cur_cheese = ExpMap(cov_path, '', '', '', '', '', Quantity(0.5, 'keV'), Quantity(2.0, 'keV'))
    with fits.open(cov_path) as covero:
        if row_ind == 0:
            print(covero[0].header['MISSION*'])
            
        cov_arr = covero[0].data
        nustar_cov_arr = cov_arr[4, :, :]
        
        field_nustar_cov_frac.append(nustar_cov_arr.sum() / (nustar_cov_arr.shape[0]*nustar_cov_arr.shape[1]))
        
        pix_cen = Quantity([nustar_cov_arr.shape[0]/2, nustar_cov_arr.shape[1]/2], 'pix').round(0).astype(int)
        rad = Quantity(row['R500'], 'Mpc')
        
        pix_rad = physical_rad_to_pix(cur_cheese, rad, pix_cen, row['redshift'], cosmo)
        
        rad_mask = annular_mask(pix_cen, np.array([0]), np.array([pix_rad.value]), nustar_cov_arr.shape)
        msk_nustar_cov = nustar_cov_arr*rad_mask
        r500_nustar_cov_frac.append(msk_nustar_cov.sum() / rad_mask.sum())
        
        rel_samp.loc[row_ind, 'NUSTAR_R500_FRAC'] = r500_nustar_cov_frac[row_ind]

### Distribution of coverage of 3.06$^{\circ}$x3.06$^{\circ}$ field centered on MCXC position

In [ ]:
plt.figure(figsize=(7, 6))
plt.minorticks_on()
plt.tick_params(which='both', direction='in', top=True, right=True)
plt.hist(field_nustar_cov_frac, bins='auto', color='tab:cyan', alpha=0.7, label='NuSTAR')
plt.ylabel('N', fontsize=15)
plt.xlabel(r'Fraction of coverage of wide field', fontsize=15)

plt.legend(loc='best')
plt.tight_layout()
plt.show()

### Distribution of coverage of MCXC $R_{500}$ centered on MCXC position

In [ ]:
plt.figure(figsize=(7, 6))
plt.minorticks_on()
plt.tick_params(which='both', direction='in', top=True, right=True)
plt.hist(r500_nustar_cov_frac, bins='auto', color='tab:cyan', alpha=0.7, label='NuSTAR')

plt.ylabel('N', fontsize=15)
plt.xlabel(r'Fraction of coverage of MCXC $R_{500}$', fontsize=15)

plt.legend(loc='best')
plt.tight_layout()
plt.show()

## No NuSTAR Coverage

The clusters with no NuSTAR observations are all potential targets for this proposal, though we will prioritise based on different criteria. First of all though, there are several clusters which have been found to have planned NuSTAR observations, we will mark them as fully covered in the dataframe (though of course that may not be the case):

### Planned NuSTAR Observations

In [ ]:
planned = [0, 2, 4, 5]

sel = rel_samp['LoVoCCSID'].isin(planned)
rel_samp.loc[sel, 'NUSTAR_R500_FRAC'] = 1

sel = samp['LoVoCCSID'].isin(planned)
samp.loc[sel, 'NUSTAR_R500_FRAC'] = 1

In [ ]:
poss_targ = rel_samp[rel_samp['NUSTAR_R500_FRAC'] < 0.5]
poss_targ.to_csv("poss_nustar_targets.csv", index=False)
poss_targ