# X-LoVoCCS: Summarising the data archive used in the X-LoVoCCS-I paper

## Import statements

In [28]:
import pandas as pd
import numpy as np
import json
from matplotlib import pyplot as plt

%matplotlib inline

## Loading data files

Important considerations for this dataset:

* The galaxy clusters investigated in the first X-LoVoCCS publication are a subset (58) of the whole LoVoCCS sample (147). They were originally presented in the second LoVoCCS paper (LoVoCCS-II; [Shenming et al. 2022](https://ui.adsabs.harvard.edu/abs/2024ApJ...974...69F/abstract)), and all have LoVoCCS 2D weak-lensing aperture mass maps available.
* As the X-LoVoCCS sample has additional entries in the cases where multiple X-ray components are evident in modern observations (e.g. LoVoCCS-41 becomes LoVoCCS-41**A**, **B**, and **C**), we also load the original LoVoCCS selection sample, where MCXC entries are linked to whole LoVoCCS clusters.

### X-LoVoCCS-I base sample

The general sample file for the X-LoVoCCS-I publication:

In [14]:
xlovoccsI_base = pd.read_csv("../../sample_files/paper_specific_subsamples/X-LoVoCCSI.csv")
xlovoccsI_base.head(6)

,LoVoCCSID,parent_LoVoCCSID,Name,start_ra,start_dec,MCXC_Redshift,MCXC_R500,MCXC_RA,MCXC_DEC,manual_xray_ra,manual_xray_dec,MCXC_Lx500_0.1_2.4
0,1,1,A2029,227.734300,5.745471,0.0766,1.3344,227.73000,5.720000,227.734300,5.745471,8.726709e+44
1,2,2,A401,44.740000,13.580000,0.0739,1.2421,44.74000,13.580000,NaN,NaN,6.088643e+44
2,4A,4,A85North,10.458750,-9.301944,0.0555,1.2103,10.45875,-9.301944,NaN,NaN,5.100085e+44
3,4B,4,A85South,10.451487,-9.460007,0.0555,1.2103,10.45875,-9.301944,10.451487,-9.460007,5.100085e+44
4,5,5,A3667,303.157313,-56.845978,0.0556,1.1990,303.13000,-56.830000,303.157313,-56.845978,4.871933e+44
5,7,7,A3827,330.480000,-59.950000,0.0980,1.1367,330.48000,-59.950000,NaN,NaN,4.204419e+44

### LoVoCCS MCXC entries

The subset of the MCXC catalog that constitutes the original LoVoCCS selection:

In [6]:
lovoccs_mcxc = pd.read_csv("../../sample_files/mcxc_lovoccs.csv")
lovoccs_mcxc.head(6)

,NAME,ALT_NAME,OTHER_NAMES,MCXC_RA,MCXC_DEC,MCXC_REDSHIFT,CATALOG_NAME,SUB_CATALOG_NAME,LINEAR_SCALE_FACTOR,LX_500,...,NOTES,OVERLAP_CAT_1,OVERLAP_CAT_2,OVERLAP_CAT_3,OVERLAP_CAT_4,LX_RATIO_CAT_1,LX_RATIO_CAT_2,LX_RATIO_CAT_3,LX_RATIO_CAT_4,LoVoCCSID
0,MCXC J1558.3+2713,RXC J1558.3+2713,A2142 ...,239.5858,27.2269,0.0894,NORAS/REFLEX,NORAS,1.669,1.067609e+45,...,L,BCS,NaN,NaN,NaN,1.045,NaN,NaN,NaN,0
1,MCXC J1510.9+0543,A2029,A2029 ...,227.7292,5.7200,0.0766,BCS,BCS,1.451,8.726709e+44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,MCXC J0258.9+1334,RXC J0258.9+1334,A0401 ...,44.7396,13.5794,0.0739,NORAS/REFLEX,NORAS,1.405,6.088643e+44,...,L,BCS,NaN,NaN,NaN,0.880,NaN,NaN,NaN,2
3,MCXC J1348.8+2635,RXC J1348.8+2635,A1795 ...,207.2208,26.5956,0.0622,NORAS/REFLEX,NORAS,1.199,5.478067e+44,...,NaN,BCS,NaN,NaN,NaN,1.197,NaN,NaN,NaN,3
4,MCXC J0041.8-0918,RXC J0041.8-0918,A0085 ...,10.4588,-9.3019,0.0555,NORAS/REFLEX,REFLEX,1.078,5.100085e+44,...,"L,losStr",SGP,NaN,NaN,NaN,0.945,NaN,NaN,NaN,4
5,MCXC J2012.5-5649,RXC J2012.5-5649,A3667 ...,303.1271,-56.8319,0.0556,NORAS/REFLEX,REFLEX,1.080,4.871933e+44,...,"L,losStr",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

### X-LoVoCCS relevant observations index

A set of information produced during the X-LoVoCCS-Data coverage map generation process, linking specific 'parent' LoVoCCS IDs (i.e. as selected from MCXC, prior to some clusters being split into multiple components using modern observations) to unique ObsIDs from a variety of X-ray telescopes:

In [8]:
with open("../../data_notes/rel_obs_for_clusters.json", 'r') as reado:
    xlovoccs_rel_obs = json.load(reado)

# As an example
xlovoccs_rel_obs['LoVoCCS-123']

{'xmm_pointed': ['0861150201',
  '0057740401',
  '0821310101',
  '0030140301',
  '0201780101',
  '0861150301',
  '0030140201',
  '0030140101',
  '0057740301'],
 'chandra': ['4198', '15635', '4403', '10746', '8268', '10745', '15634'],
 'rosat_pointed_pspc': ['RP300093N00', 'RP701155N00', 'RP800374N00'],
 'rosat_all_sky': ['RS932330N00', 'RS932232N00'],
 'swift_xrt': ['00033205005',
  '00033205007',
  '00033205001',
  '00037154019',
  '00033205009',
  '07017525001',
  '07017314001',
  '00033205004',
  '07017508001',
  '00034679001',
  '07017097001',
  '00033205003',
  '00033205008',
  '07017509001',
  '00033205002',
  '03108418001'],
 'asca': ['86016000', '84057000', '86014000', '86015000'],
 'suzaku': ['808107010', '808104010'],
 'erosita_all_sky_de_dr1': ['194120']}

## Counting observations near to X-LoVoCCS-I clusters

The relevant observations dictionary that we loaded in links particular clusters to particular observations by X-ray telescopes - though it is important to recognise that these observations aren't yet guaranteed to be **actually of** the cluster of interest, as they could just be nearby.

### Relevant observations dataframe

In this case, a Pandas dataframe will be easier to work with than the dictionary that we loaded in - once converted we can filter to select only the clusters relevant to X-LoVoCCS-I - then we can count the number of observations by each telescope possibly connected to each system:

In [17]:
all_rel_obs = pd.DataFrame.from_dict(xlovoccs_rel_obs).T
all_rel_obs.head(3)

,xmm_pointed,chandra,rosat_pointed_pspc,rosat_pointed_hri,rosat_all_sky,swift_xrt,asca,suzaku,nustar_pointed,erosita_all_sky_de_dr1
LoVoCCS-0,"[0111870301, 0112240401, 0694440601, 069444020...","[24490, 23844, 16565, 17168, 7692, 24488, 1228...","[RP800415N00, RP800096N00, RP800551N00, RP1500...","[RH800687N00, RH800640N00]",[RS931239N00],[00089945001],"[81005000, 81004000]","[801055010, 802030010]",NaN,NaN
LoVoCCS-1,"[0744410901, 0822350101, 0551780301, 010992010...","[29418, 25863, 25825, 29438, 10437, 27848, 272...","[RP800275N00, RP800275A01, RP800161N00, RP8002...","[RH800223N00, RH800223A02, RH800223A01, RH8009...",[RS931641N00],"[00036339003, 03111929001, 00035188001, 031119...","[83040010, 81023000, 85061000, 83040020, 85058...","[804024050, 100006010, 804024020, 804024030, 1...","[60401024002, 70660001002, 60801046002]",NaN
LoVoCCS-2,"[0112260201, 0112260101, 0112260401, 092167010...","[27549, 27560, 27562, 10419, 10416, 22882, 272...","[RP800235N00, RP180248N00, RP180250N00, RP1802...","[RH800850A01, RH800823N00, RH800850N00, RH8009...",[RS931508N00],"[07030661001, 00094101002, 07030660001, 070306...","[82009000, 82010000, 82008000]","[801020010, 808005010, 808007010, 808006010]",NaN,NaN

Now we cut it down:

In [31]:
rel_rel_obs = all_rel_obs.loc[xlovoccsI_base['parent_LoVoCCSID'].apply(lambda x: 'LoVoCCS-'+str(x))]
rel_rel_obs.head(3)

,xmm_pointed,chandra,rosat_pointed_pspc,rosat_pointed_hri,rosat_all_sky,swift_xrt,asca,suzaku,nustar_pointed,erosita_all_sky_de_dr1
LoVoCCS-1,"[0744410901, 0822350101, 0551780301, 010992010...","[29418, 25863, 25825, 29438, 10437, 27848, 272...","[RP800275N00, RP800275A01, RP800161N00, RP8002...","[RH800223N00, RH800223A02, RH800223A01, RH8009...",[RS931641N00],"[00036339003, 03111929001, 00035188001, 031119...","[83040010, 81023000, 85061000, 83040020, 85058...","[804024050, 100006010, 804024020, 804024030, 1...","[60401024002, 70660001002, 60801046002]",NaN
LoVoCCS-2,"[0112260201, 0112260101, 0112260401, 092167010...","[27549, 27560, 27562, 10419, 10416, 22882, 272...","[RP800235N00, RP180248N00, RP180250N00, RP1802...","[RH800850A01, RH800823N00, RH800850N00, RH8009...",[RS931508N00],"[07030661001, 00094101002, 07030660001, 070306...","[82009000, 82010000, 82008000]","[801020010, 808005010, 808007010, 808006010]",NaN,NaN
LoVoCCS-4,"[0744411901, 0744411701, 0065140101, 074493030...","[15174, 4888, 4884, 4885, 4886, 904, 4887, 151...","[RP800174A00, RP800174A01, RP800250N00]",[RH800271N00],"[RS931802N00, RS931902N00]","[00049952003, 00049952007, 00034928001, 000499...","[81024000, 81024010]","[801041010, 807136010]",NaN,NaN

### Counting X-ray observations

In [35]:
rel_rel_obs_num = rel_rel_obs.map(lambda x: len(x), na_action='ignore').fillna(0).astype(int)
rel_rel_obs_num

,xmm_pointed,chandra,rosat_pointed_pspc,rosat_pointed_hri,rosat_all_sky,swift_xrt,asca,suzaku,nustar_pointed,erosita_all_sky_de_dr1
LoVoCCS-1,24,59,4,5,1,23,6,11,3,0
LoVoCCS-2,8,24,5,4,1,51,3,4,0,0
LoVoCCS-4,8,13,3,1,2,7,2,2,0,0
LoVoCCS-4,8,13,3,1,2,7,2,2,0,0
LoVoCCS-5,18,13,2,1,2,9,3,5,1,1
...,...,...,...,...,...,...,...,...,...,...
LoVoCCS-121,3,1,2,1,3,4,1,0,0,3
LoVoCCS-122,0,0,0,0,2,0,0,0,0,1
LoVoCCS-123,9,7,3,0,2,16,4,2,0,1
LoVoCCS-131,17,10,5,7,1,26,2,3,1,2
LoVoCCS-134,5,1,0,1,2,1,0,0,0,2